spring:
  cloud:
    stream:
      bindings:
        input:
          destination: input
          group: input-group
          binder: rabbit
        output:
          destination: output
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: "rss"
          output:
            producer:
              bindingRoutingKey: "json.rss"
              routing-key-expression: '"json.rss"'
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
                virtual-host: /
  redis:
    host: localhost
    port: 6379
logging:
  level:
    fr:
      asso:
        placeholder: DEBUG