## default connection pool
spring:
  data:
    rest:
      base-path: "/api"
  datasource:
    username: "postgres"
    password: "1iAlOmJ4b2tRB10Ek8pV8HM"
    url: "jdbc:postgresql://163.172.90.123:31708/postgres"
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
