{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-source-rss.serviceAccountName" . }}
  labels:
{{ include "data-source-rss.labels" . | nindent 4 }}
{{- end -}}
